repos:
-   repo: local
    hooks:
    -   id: black
        name: black
        entry: black .
        language: system
        types: [ python ]
        pass_filenames: false

    -   id: flake8
        name: flake8
        entry: flake8 .
        language: system
        types: [ python ]
        pass_filenames: false

    -   id: isort
        name: isort
        entry: isort .
        language: system
        types: [ python ]
        pass_filenames: false